## Setup

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
!rm -rf /kaggle/working/qlora_checkpoints

In [4]:
import os
os.chdir("/kaggle/working")
!git clone https://github.com/hossamhamdy333/AI_Portfolio.git
os.chdir(f"/kaggle/working/AI_Portfolio")

fatal: destination path 'AI_Portfolio' already exists and is not an empty directory.

In [5]:
PROJECT_FOLDER = "sql_finetune"
base = f"/kaggle/working/AI_Portfolio/{PROJECT_FOLDER}"
os.chdir(f"/kaggle/working/AI_Portfolio")
!git pull origin main --rebase
import yaml
with open(f"{base}/configs/config.yaml") as f:
    config = yaml.safe_load(f)
config

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Already up to date.

{'model': {'base_model': 'Qwen/Qwen2.5-Coder-1.5B-Instruct'},
 'data': {'hf_dataset': 'b-mc2/sql-create-context',
  'random_seed': 42,
  'train_size': 3000,
  'val_size': 300},
 'lora': {'r': 16,
  'lora_alpha': 32,
  'target_modules': ['q_proj', 'k_proj', 'v_proj', 'o_proj'],
  'lora_dropout': 0.05,
  'bias': 'none'},
 'training': {'num_train_epochs': 3,
  'per_device_train_batch_size': 8,
  'gradient_accumulation_steps': 2,
  'learning_rate': 0.0002,
  'max_seq_length': 512,
  'logging_steps': 10,
  'save_steps': 50,
  'save_total_limit': 2,
  'warmup_ratio': 0.03}}

In [6]:
!pip install -q "trl<0.15.0" transformers peft bitsandbytes accelerate datasets wandb pandas pyarrow

In [7]:
os.chdir(base)
import pandas as pd
train_df = pd.read_parquet(f"{base}/data/train.parquet")
print(train_df.shape)
train_df.head(2)

(3000, 3)

,question,context,answer
0,What place had a ribbon below 9.8 and a 19.2 t...,"CREATE TABLE table_name_23 (place INTEGER, rib...",SELECT MAX(place) FROM table_name_23 WHERE rib...
1,Who is the opponent in 1992?,"CREATE TABLE table_name_17 (opponent VARCHAR, ...",SELECT opponent FROM table_name_17 WHERE year ...

### Tokenizer + prompt formatting

In [8]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(config['model']['base_model'])
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [9]:
def format_prompt(question, context):
    return (
        "### Task:\n"
        "Write a SQL query that answers the question, given the database schema.\n\n"
        f"### Schema:\n{context}\n\n"
        f"### Question:\n{question}\n\n"
        "### SQL:\n"
    )

In [10]:
def format_example(row):
    messages = [
        {
            "role": "system",
            "content": "You are a SQL expert. Output ONLY the raw SQL query. Do not wrap it in markdown code blocks, and do not provide any explanations.",
        },
        {"role": "user", "content": f"Schema:\n{row['context']}\n\nQuestion:\n{row['question']}"},
        {"role": "assistant", "content": row['answer']}
    ]
    return tokenizer.apply_chat_template(messages, tokenize=False)

train_df['text'] = train_df.apply(format_example, axis=1)
print(train_df['text'].iloc[0])

<|im_start|>system
You are a SQL expert. Output ONLY the raw SQL query. Do not wrap it in markdown code blocks, and do not provide any explanations.<|im_end|>
<|im_start|>user
Schema:
CREATE TABLE table_name_23 (place INTEGER, ribbon VARCHAR, total VARCHAR)

Question:
What place had a ribbon below 9.8 and a 19.2 total?<|im_end|>
<|im_start|>assistant
SELECT MAX(place) FROM table_name_23 WHERE ribbon < 9.8 AND total = 19.2<|im_end|>

In [11]:
from datasets import Dataset
train_dataset = Dataset.from_pandas(train_df[['text']])
train_dataset

Dataset({
    features: ['text'],
    num_rows: 3000
})

### Sanity check

In [12]:
_sample_ids = tokenizer(train_df['text'].iloc[0], truncation=True, max_length=config['training']['max_seq_length'])['input_ids']
print("last 5 token ids:", _sample_ids[-5:])
print("eos_token_id:", tokenizer.eos_token_id)
assert tokenizer.eos_token_id in _sample_ids[-3:], "EOS not found near end of tokenized sequence "
print("EOS present ")

last 5 token ids: [24, 13, 17, 151645, 198]
eos_token_id: 151645
EOS present

### Load base model in 4-bit (QLoRA)

In [15]:
import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    config['model']['base_model'],
    quantization_config=bnb_config,
    device_map="auto"
)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [16]:
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=config['lora']['r'],
    lora_alpha=config['lora']['lora_alpha'],
    target_modules=config['lora']['target_modules'],
    lora_dropout=config['lora']['lora_dropout'],
    bias=config['lora']['bias'],
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

trainable params: 4,358,144 || all params: 1,548,072,448 || trainable%: 0.2815

### W&B login

In [17]:
import getpass
import wandb

wandb_key = getpass.getpass("Enter your W&B API key: ").strip()
wandb.login(key=wandb_key)

Enter your W&B API key:  ········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: hossam3759180 (hossam3759180-higher-technological-institute) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [18]:
checkpoint_dir = "/kaggle/working/qlora_checkpoints"

import glob
existing_checkpoints = sorted(
    glob.glob(f"{checkpoint_dir}/checkpoint-*"),
    key=lambda p: int(p.split("-")[-1])
)
resume_path = existing_checkpoints[-1] if existing_checkpoints else None

if resume_path:
    print(f"Found existing checkpoint, will resume from: {resume_path}")
else:
    print("No existing checkpoint found, starting fresh from step 0.")

No existing checkpoint found, starting fresh from step 0.

In [20]:
training_args = SFTConfig(
    output_dir="/kaggle/working/qlora_checkpoints",
    num_train_epochs=config['training']['num_train_epochs'],
    per_device_train_batch_size=config['training']['per_device_train_batch_size'],
    gradient_accumulation_steps=config['training']['gradient_accumulation_steps'],
    learning_rate=config['training']['learning_rate'],
    max_seq_length=config['training']['max_seq_length'],   # renamed
    dataset_text_field="text",
    logging_steps=config['training']['logging_steps'],
    save_steps=config['training']['save_steps'],
    save_total_limit=config['training']['save_total_limit'],
    warmup_ratio=config['training']['warmup_ratio'],
    fp16=False,
    bf16=True,
    report_to="wandb",
    use_liger_kernel=False,
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [21]:
import os
import wandb
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    train_dataset=train_dataset,
    processing_class=tokenizer,
    args=training_args,
)

os.chdir(base)

wandb.init(
    project="sql_finetune",
    name="sql_qlora",
    config={
        "base_model": config['model']['base_model'],
        "learning_rate": config['training']['learning_rate'],
        "num_train_epochs": config['training']['num_train_epochs'],
        "train_rows": len(train_dataset),
        "resumed_from_checkpoint": resume_path is not None,
    },
)

train_result = trainer.train(resume_from_checkpoint=resume_path)
wandb.finish()

print("Training complete.")
print(f"Final train loss: {train_result.training_loss:.4f}")

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Training complete.
Final train loss: 0.7095

### Save adapter

In [22]:
adapter_path = f"{base}/outputs/models/sql_qlora_adapter"
model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)

('/kaggle/working/AI_Portfolio/sql_finetune/outputs/models/sql_qlora_adapter/tokenizer_config.json',
 '/kaggle/working/AI_Portfolio/sql_finetune/outputs/models/sql_qlora_adapter/chat_template.jinja',
 '/kaggle/working/AI_Portfolio/sql_finetune/outputs/models/sql_qlora_adapter/tokenizer.json')

## Github Push

In [27]:
import getpass
GITHUB_USERNAME = "hossamhamdy333"
GITHUB_TOKEN = getpass.getpass("GitHub token: ")
REPO_NAME = "AI_Portfolio"

os.chdir(f"/kaggle/working/AI_Portfolio")
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

GitHub token:  ········

In [28]:
os.chdir(f"/kaggle/working/AI_Portfolio")
!git config --global user.email "210591705+hossamhamdy333@users.noreply.github.com"
!git config --global user.name "Hossam Hamdy"
!git pull origin main --rebase
!git add .
!git commit -m "finetuned adapter eval"
!git push origin main

From https://github.com/hossamhamdy333/AI_Portfolio
 * branch            main       -> FETCH_HEAD
Current branch main is up to date.
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 17.38 MiB | 7.81 MiB/s, done.
Total 12 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/hossamhamdy333/AI_Portfolio.git
   09bf231..e5fd5b4  main -> main